import { IPlayerJSON } from "../Interfaces";

const gameJSON: { players: IPlayerJSON[] } & {
  turn: number | null;
  roll: number | null;
} = {
  turn: 0,
  roll: null,
  players: [
    {
      color: 0,
      currentTurn: false,
      pieceCount: 4,
      dieFace: -1,
      pieces: [
        {
          color: 0,
          isOut: false,
          isInHouse: true,
          isInPlay: false,
          index: -1,
          isSafe: true,
          inHomeRun: false,
        },
        {
          color: 0,
          isOut: false,
          isInHouse: true,
          isInPlay: false,
          index: -1,
          isSafe: true,
          inHomeRun: false,
        },
        {
          color: 0,
          isOut: false,
          isInHouse: true,
          isInPlay: false,
          index: -1,
          isSafe: true,
          inHomeRun: false,
        },
        {
          color: 0,
          isOut: false,
          isInHouse: true,
          isInPlay: false,
          index: -1,
          isSafe: true,
          inHomeRun: false,
        },
      ],
    },
    {
      color: 1,
      currentTurn: false,
      pieceCount: 4,
      dieFace: -1,
      pieces: [
        {
          color: 1,
          isOut: false,
          isInHouse: true,
          isInPlay: false,
          index: -1,
          isSafe: true,
          inHomeRun: false,
        },
        {
          color: 1,
          isOut: false,
          isInHouse: true,
          isInPlay: false,
          index: -1,
          isSafe: true,
          inHomeRun: false,
        },
        {
          color: 1,
          isOut: false,
          isInHouse: true,
          isInPlay: false,
          index: -1,
          isSafe: true,
          inHomeRun: false,
        },
        {
          color: 1,
          isOut: false,
          isInHouse: true,
          isInPlay: false,
          index: -1,
          isSafe: true,
          inHomeRun: false,
        },
      ],
    },
    {
      color: 2,
      currentTurn: false,
      pieceCount: 4,
      dieFace: -1,
      pieces: [
        {
          color: 2,
          isOut: false,
          isInHouse: true,
          isInPlay: false,
          index: -1,
          isSafe: true,
          inHomeRun: false,
        },
        {
          color: 2,
          isOut: false,
          isInHouse: true,
          isInPlay: false,
          index: -1,
          isSafe: true,
          inHomeRun: false,
        },
        {
          color: 2,
          isOut: false,
          isInHouse: true,
          isInPlay: false,
          index: -1,
          isSafe: true,
          inHomeRun: false,
        },
        {
          color: 2,
          isOut: false,
          isInHouse: true,
          isInPlay: false,
          index: -1,
          isSafe: true,
          inHomeRun: false,
        },
      ],
    },
    {
      color: 3,
      currentTurn: false,
      pieceCount: 4,
      dieFace: -1,
      pieces: [
        {
          color: 3,
          isOut: false,
          isInHouse: true,
          isInPlay: false,
          index: -1,
          isSafe: true,
          inHomeRun: false,
        },
        {
          color: 3,
          isOut: false,
          isInHouse: true,
          isInPlay: false,
          index: -1,
          isSafe: true,
          inHomeRun: false,
        },
        {
          color: 3,
          isOut: false,
          isInHouse: true,
          isInPlay: false,
          index: -1,
          isSafe: true,
          inHomeRun: false,
        },
        {
          color: 3,
          isOut: false,
          isInHouse: true,
          isInPlay: false,
          index: -1,
          isSafe: true,
          inHomeRun: false,
        },
      ],
    },
  ],
};
export default gameJSON;
